README.md
api/common.go
pkg/datagatherer/datagatherer.go
pkg/datagatherer/eks/eks.go
pkg/datagatherer/gke/gke.go
pkg/datagatherer/k8s/client.go

Add badges and reword some documentation.

Add badges

---

README.md

Highlight path in readme

---

Makefile

Push canary docker image

---

examples/reports/pods.json
preflight-packages/examples.jetstack.io/pods_basic/policy-manifest.yaml

Appeared to be incomplete - seemed like a simple first PR...

Update policy description

---

OWNERS

Add Wil and Charlie to OWNERS

---

docs/how_to_write_packages.md

Update manual now that 'preflight package test' is a feature

---

Dockerfile
Makefile
go.sum

Signed-off-by: paulwilljones <paul.jones@jetstack.io>

Add Make install target to facilitate version info in Docker

---

go.sum

I'm finding this file is updated with the following changes when I run
go test / anything go.
```
$ go version
go version go1.13.6 linux/amd64
```

Update go mod sum file

---

pkg/exporter/json_test.go
pkg/lint/manifest_test.go
preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
preflight-packages/jetstack.io/pods/policy-manifest.yaml

Closes https://github.com/jetstack/preflight/issues/45

Decrease package schema-version

---

Makefile
preflight-packages/examples.jetstack.io/aks_basic/aks.rego
preflight-packages/examples.jetstack.io/aks_basic/aks_test.rego

As we add more full packages to the repo we should also be running lint and test on them in CI to ensure they are correctly formatted and working.

Add lint rule, update test rule, add both to CI test rule

---

deployment/kubernetes/overlays/scanner/config/preflight.yaml
examples/gke.preflight.yaml
examples/pods.preflight.yaml

Replace sample pods package with full pods package in examples

---

README.md
docs/configuration.md
docs/datagatherers/gke.md
docs/datagatherers/k8s_pods.md

Update docs and README, add additional info.

Update docs and README

---

README.md

Regenerate toc in readme

---

README.md

Fix README markdown heading

---

api/report.go
pkg/exporter/json_test.go
pkg/reports/reports.go
pkg/reports/reports_test.go

This has proven to be useful for debugging.

Show schema-version on report

---

pkg/output/local.go

Index files must be overwritten to the same path. Should have happened as part of #70

Allow existing local indexes to be overwritten

---

preflight-packages/jetstack.io/pods/pods.rego
preflight-packages/jetstack.io/pods/pods_test.rego
preflight-packages/jetstack.io/pods/policy-manifest.yaml

Add rules for node and pod affinity

---

examples/aks.preflight.yaml

Fix typo in example AKS Preflight config

---

deployment/kubernetes/overlays/scanner/config/preflight.yaml
examples/aks.preflight.yaml
examples/gke.preflight.yaml
examples/pods.preflight.yaml

Updating after https://github.com/jetstack/preflight/pull/67 was merged

Update preflight.yamls to new config

---

agent.yaml
api/datareading.go
api/reading.go
cmd/agent.go
cmd/echo.go
go.mod
go.sum
pkg/agent/config.go
pkg/agent/config_test.go
pkg/agent/run.go

Make agent upload data

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/document-research.md
.github/ISSUE_TEMPLATE/package-suggestion.md
.github/ISSUE_TEMPLATE/user-story.md

Add issue templates

---

cmd/check.go
cmd/test.go
pkg/packagesources/local/local.go
pkg/packagesources/packagesources.go
pkg/packaging/eval.go
pkg/packaging/packaging.go
pkg/packaging/test.go

This extracts from #82 the refactorization of the package sources.
I have reworked the constructor for the actual package sources.

Refactor package source and package source config

---

pkg/datagatherer/aks/aks.go
pkg/datagatherer/eks/eks.go
pkg/datagatherer/gke/gke.go
pkg/datagatherer/k8s/generic.go
pkg/datagatherer/local/local.go

Change DataGatherers constructors to return DataGatherer interface

---

pkg/packagesources/local/local.go

Change PackageSource constructors to return PackageSource interface

---

cmd/check.go
pkg/output/azblob/azblob.go
pkg/output/cli/cli.go
pkg/output/gcs/gcs.go
pkg/output/local/local.go
pkg/output/output.go

Refactor Outputs to use new pattern for Config.

Refactor output config

---

agent.yaml
pkg/agent/config.go
pkg/agent/config_data_gatherers.go
pkg/agent/config_data_gatherers_test.go
pkg/agent/config_test.go
pkg/agent/dummy_data_gatherer.go
pkg/agent/run.go
pkg/datagatherer/aks/aks.go
pkg/datagatherer/eks/eks.go
pkg/datagatherer/gke/gke.go
pkg/datagatherer/k8s/generic.go
pkg/datagatherer/local/local.go
pkg/packagesources/local/local.go

Fixes https://github.com/jetstack/preflight/issues/90

Implement data gathering functionality of agent

---

cmd/echo.go

In preparation for #92, this makes the echo server accept a token.

Echo server to accept auth token

---

cmd/check.go

Change dataGatherersConfig variable creation to instantiate map

Fix refactor config decoding in check function

---

agent.yaml
pkg/agent/run.go

Agent to use auth token

---

api/report.go

Add GenReportMetadata function to Report

---

OWNERS

Allow akvile to close issues

---

OWNERS

Make other approvers reviewers

---

README.md

Closes https://github.com/jetstack/preflight/issues/117

Fix readme whitespace

---

README.md

This PR updates the project README to warn about and explain the changes taking place in the repo.

Readme check disclaimer

---

examples/pods.preflight.yaml
internal/checkconfig/checkconfig.go
pkg/datagatherer/k8s/generic.go
pkg/datagatherer/k8s/generic_test.go

Kubernetes data gatherer exclude some namespaces

---

pkg/datagatherer/k8s/generic.go

Fix secret redaction group check to change Core to core

---

Makefile

Fix bundle creation

---

cmd/agent.go
pkg/agent/run.go

Add a period flag with a default period of 1 hour.

Add period flag

---

OWNERS

Add james-w to OWNERS

---

pkg/datagatherer/k8s/generic.go
pkg/datagatherer/k8s/generic_test.go

If the annotation is set (when the resource was applied with kubectl)
then set the string value to redacted instead.
Fixes https://github.com/jetstack/preflight/issues/151
(thanks @TomHoward for the heads up!)

Redact the last applied configuration annotation

---

docs/datagatherers/gke.md

Show how to configure gke datagatherer permissions

---

examples/cert-manager-agent.yaml

This is a reference to share with those interested in using the CM package as this is not documented elsewhere.

Add example cert-manager agent yaml

---

docs/datagatherers/gke.md

This fixes an error in the documentation for the GKE data-gatherer.

Fix GKE config in GKE data-gatherer doc

---

Makefile

Add OAuth2 configuration for preflight.jetstack.io

---

Dockerfile
Makefile

Pass oauth flags to docker build

---

pkg/client/accessToken.go

This fixes the issue with some credentials not working.

Encode payload in POST to get access token

---

docs/datagatherers/gke.md

The format for the configuration of this datagatherer has changed.

Update GKE config docs

---

agent.yaml
cmd/agent.go
go.mod
go.sum
pkg/agent/config_test.go
pkg/agent/dummy_data_gatherer.go
pkg/agent/run.go

A ticker manages an exponential backoff algorithm
This uses: https://pkg.go.dev/github.com/cenkalti/backoff/
The variables e.g. maxtime or intervals can be changed through backOff.
Successful dataGatherers are tracked through a map.
Only those not in the map are retried.
WIP: Wrap this in a function which can be tested more rigorously
Signed-off-by: Jamie Leppard <JammyL@users.noreply.github.com>

Edits data gathering process to retry dataGatherer

---

docs/datagatherers/k8s-dynamic.md
pkg/datagatherer/k8s/dynamic.go
pkg/datagatherer/k8s/dynamic_test.go

This allows crt content to be used in package rules.

Retain certs when posting tls secrets

---

docs/datagatherers/gke.md

Signed-off-by: Oluwole Fadeyi <oluwole.fadeyi@gmail.com>

Update gke package configuration docs

---

go.mod
go.sum
pkg/datagatherer/k8s/dynamic.go
pkg/datagatherer/k8s/dynamic_test.go

Replaces https://github.com/jetstack/preflight/pull/202

Remove managed fields

---

pkg/datagatherer/k8s/fieldfilter_test.go

Replicates test confirming behaviour for non-secret resources in https://github.com/jetstack/preflight-platform/pull/679

Add a test for filtering a non secret resource

---

cmd/agent.go
pkg/agent/config.go
pkg/agent/config_test.go
pkg/agent/run.go

This will allow users to update the period on which data is sent by only
applying a new config.

Load the period from config file

---

pkg/agent/run.go

Do not require period if one-shot mode

---

pkg/agent/run.go

Log when data is sent to the backend ok

---

go.mod
go.sum
pkg/echo/echo.go

This adds colours to echo sever output.
fixes #242 
Signed-off-by: wenlin <wenlin.yi@jetstack.io>

Created echo color fix branch

---

agent.yaml

Some small fixes to the agent.yaml file
fixes #244

Fixed agent config file

---

cmd/echo.go
pkg/echo/echo.go

Use compact flag to switch echo output to compact format.
fixes #245

Add the compact flag

---

cmd/echo.go
pkg/echo/echo.go

fixes #249 
Signed-off-by: wenlin <wenlin.yi@jetstack.io>

Remove auth token from echo server

---

go.mod
go.sum
pkg/permissions/generate.go
pkg/permissions/generate_test.go

IncludeNamespaces in RoleBindings out
#250

Cluster role binding

---

README.md

docs: Correct documentation link

---

deploy/charts/jetstack-agent/Chart.yaml
deploy/charts/jetstack-agent/templates/NOTES.txt
deploy/charts/jetstack-agent/templates/deployment.yaml

Closes #436 
Also updates the Notes to fix an issue in the 3rd point + add command to view the relevant secret.
Increment chart as a patch release as none of the issues mentioned affect current released version running.
Signed-off-by: Peter Fiddes <peter.fiddes@gmail.com>

bug: Fix deployment template for configmap volume 

---

agent.yaml

This fixes the example configuration for the agent.

Fix agent configuration for venafi-cloud

---

go.mod

chore(go): Update golang version

---

deploy/charts/jetstack-agent/Chart.yaml
deploy/charts/jetstack-agent/README.md
deploy/charts/jetstack-agent/tests/__snapshot__/configuration_test.yaml.snap

Bump minor version to release the chart change to be able to add Volumes & VolumeMounts from #540.

chore: Upgrade chart version to 0.4.0 for jetstack-agent

---

deploy/charts/venafi-kubernetes-agent/Chart.yaml
deploy/charts/venafi-kubernetes-agent/README.md
deploy/charts/venafi-kubernetes-agent/values.yaml

This cuts a release with https://github.com/jetstack/jetstack-secure/pull/546 in

release: 0.1.48

---

README.md

**Context:** this is an outcome of the retro we had with @tfadeyi, @SgtCoDFish, and @inteon.

Release Process: Remind us to post a message to the #venctl Slack channel
