- Makefile
- go.mod
- go.sum
This was causing some problems with incompatible versions of dependencies.
> Tidy up deps

- Dockerfile
- Makefile
- README.md
- deployment/kubernetes/base/00-namespace.yaml
- deployment/kubernetes/base/01-rbac.yaml
- deployment/kubernetes/base/02-cronjob.yaml
- deployment/kubernetes/base/kustomization.yaml
- deployment/kubernetes/overlays/.gitignore
- deployment/kubernetes/overlays/sample/custom-image.yaml
- deployment/kubernetes/overlays/sample/kustomization.yaml
- deployment/kubernetes/overlays/sample/preflight.yaml
- docs/datagatherers/gke.md
- docs/datagatherers/k8s_pods.md
- docs/how_to_write_packages.md
- docs/preflight-in-cluster.md
- examples/gke.preflight.yaml
- examples/pods.preflight.yaml
- examples/reports/gke.json
- examples/reports/pods.json
- preflight-packages/examples.jetstack.io/gke_basic/gke.rego
- preflight-packages/examples.jetstack.io/gke_basic/gke_test.rego
- preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
- preflight-packages/examples.jetstack.io/pods_basic/pods.rego
- preflight-packages/examples.jetstack.io/pods_basic/pods_test.rego
- preflight-packages/examples.jetstack.io/pods_basic/policy-manifest.yaml
This adds a decent readme and some other documentation (./docs). It adds a tutorial on how to deploy preflight as a cronjob.
Additionally, it adds a Dockerfile.
> Add documentation and examples

- cmd/check.go
- docs/datagatherers/gke.md
- examples/gke.preflight.yaml
- examples/reports/gke.json
- pkg/datagatherer/gke/gke.go
`Location` works for both `Zones` and `Regions`.
Closes #9. 
> Use Location instead of Zone for gke datagatherer configuration

- Makefile
`ci-deps` will be used to install the dependencies needed for CI.
> Add ci-deps target

- Makefile
- api/report.go
- cmd/version.go
- go.mod
- go.sum
- pkg/exporter/json.go
- pkg/exporter/json_test.go
- pkg/version/version.go
This changes the `api.Report` schema to include both the version of Preflight that was used and also the additional information of the Package.
Notice this is a breaking change since we are mutating the existing `Package` property in the report to a `Package` object.
> Include preflight-version, and package information in reports

- api/report.go
Adding some more documentation and also adding `PackagingInformation` to `ReportMetadata` for completeness.
> Add some more doc and add PackageInformation to ReportMetadata struct

- deployment/terraform/gke-datagatherer/googlecloud-scanner-serviceaccount.tf
- deployment/terraform/results-bucket/googlecloud-reports-bucket-scanner-sa.tf
Only the k8s service account needs workload id user role on the SA
> Remove surplus iam member

- api/report.go
- pkg/exporter/json.go
- pkg/exporter/json_test.go
This will allow the details to be used in the frontends
Second part of https://github.com/jetstack/preflight/issues/36
> Surface violations in report JSON

- pkg/results/results.go
- pkg/results/results_test.go
We were assuming the results came from rego as `[]string`, but they were begin returned as `[]interface{}`. The logic was detecting those as invalid and erroring as a consequence.
> Change how results are unmarshaled from rego

- cmd/lint.go
- pkg/lint/manifest.go
- pkg/lint/manifest_test.go
Numeric IDs are very artificial and not meaningful at all.
I wouldn't enforce them in the linter.
Also, the linter wasn't enforcing RootQuery, but it is mandatory.
> Do not enforce numeric IDs and enforce RootQuery

- go.mod
- go.sum
- pkg/exporter/exporter.go
- pkg/exporter/exporter_test.go
- pkg/exporter/json.go
- pkg/exporter/json_test.go
- pkg/packaging/versioning.go
- pkg/packaging/versioning_test.go
This allows the `preflight_` to exist or not if the schema version of the package is lower than "0.1.0". It assumes the artificial prefix does not exist if the schema version is higher than "0.1.0".
Related: #27
> Handle the existence or not of the `preflight_` prefix in rego

- preflight-packages/examples.jetstack.io/gke_basic/gke.rego
- preflight-packages/examples.jetstack.io/gke_basic/gke_test.rego
- preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
This PR updates the GKE basic package to remove the `preflight_` prefix from rules and match its rules with the corresponding rules in the more comprehensive private GKE package.
Related to #27.
> Update GKE basic package

- preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
- preflight-packages/jetstack.io/pods/policy-manifest.yaml
Now that the `preflight_` prefix in the rego IDs has been deprecated, it is recommended that we use >= 0.1.1 for schema versions that do not use that prefix.
Related: #27 #59 
> Bump schema version for some packages

- pkg/exporter/cli.go
- pkg/exporter/exporter.go
- pkg/exporter/json.go
- pkg/exporter/json_test.go
- pkg/exporter/markdown.go
- pkg/reports/reports.go
- pkg/reports/reports_test.go
- pkg/rules/rules.go
- pkg/rules/rules_test.go
This will allow me to generate a cluster summary and update that too
when writing output to a bucket destination.
Before this, the report generation all happened in the json exporter
which meant the report data structure wasn't available for reuse.
Done as part of https://github.com/jetstack/preflight/issues/54
Related to https://github.com/jetstack/preflight/issues/1
> Extract report generation to reports package

- api/report.go
- pkg/reports/reports.go
- pkg/reports/reports_test.go
Being done as part of #54
Few things I'm not sure about here:
- if a single test for generating a clustersummary would be enough - there is a lot of duplication
- if some functions such as summarize report should be registered on the report struct.
> Report index constructors

- api/report.go
We require this to be set and empty to test the sucess of the checks
> Remove omit empty from violations

- cmd/check.go
- pkg/exporter/json.go
- pkg/exporter/json_test.go
- pkg/packaging/eval.go
- pkg/reports/reports.go
- pkg/reports/reports_test.go
This makes the command fail if a rule existed in the PolicyManifest but it was not found in the Rego package.
Since the reports are still useful, it does not fail hard and finished the execution after generating the reports.
> Make command to fail if missing Rego definition

- cmd/check.go
- go.mod
- pkg/exporter/cli.go
- pkg/exporter/cli_test.go
- pkg/exporter/exporter.go
- pkg/exporter/html.go
- pkg/exporter/intermediate.go
- pkg/exporter/json.go
- pkg/exporter/json_test.go
- pkg/exporter/markdown.go
- pkg/exporter/markdown_test.go
- pkg/exporter/raw.go
- pkg/exporter/raw_test.go
- pkg/output/azblob/azblob.go
- pkg/output/cli.go
- pkg/output/gcs/gcs.go
- pkg/output/local.go
- pkg/output/output.go
> Implement WriteIndex for cluster summaries

- cmd/check.go
When reading the `enabled-packages` from config the if `UnmarshalKey` fails it creates an empty `EnabledPackage` in the slice. The slice is then populated using the legacy config style with `GetStringSlice`.
However later the empty `EnabledPackage` causes Preflight to exit with the error:
```
2020/02/03 16:24:43 Package with ID "" was specified in configuration but it wasn't found.
```
This fix recreates the slice when falling back to the legacy method to make sure it's empty before populating.
> Recreate enabledPackages slice so it is empty

- cmd/check.go
We are not storing the timestamp nor the cluster name to the cluster summary.
This fix is not the best way of doing it. A better solution will come with #1.
> Add cluster and timestamp to summary

- api/cluster.go
- api/cluster_test.go
This is needed to a `ClusterSummary` can be unmarshaled correctly just by doing `json.Unmarshal`.
> Custom unmarshaler for ClusterSummary

- cmd/agent.go
- cmd/root.go
- go.mod
- go.sum
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
Fixes https://github.com/jetstack/preflight/issues/85
Fixes https://github.com/jetstack/preflight/issues/86
This is my go at the most simple implementation of the above issues. We needed an agent with some config. All the config parts are in place to run datagatherers and upload data.
Why did I not use the existing preflight yaml? Wil is working on this today - I would have needed to add a more fields to the config. I might well end up using what Wil refactors but this allows the work on the agent to continue either way.
> Add minimal version of the agent command

- cmd/check.go
- go.mod
- go.sum
- pkg/datagatherer/k8s/client.go
- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/k8s/generic_test.go
- pkg/datagatherer/k8s/pods.go
This is the first stage of the work to support cert-manager resources in Preflight.
This changeset refactors the 'k8s' data gatherer to not require a `runtime.Scheme` with the type being validated registered. This should make it possible to fetch CRD resources and other unknown types in future 😄
/assign @j-fuentes
> Switch k8s/pod data gatherer to use the dynamic client

- cmd/check.go
- pkg/datagatherer/aks/aks.go
- pkg/datagatherer/eks/eks.go
- pkg/datagatherer/gke/gke.go
- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/k8s/generic_test.go
- pkg/datagatherer/local/local.go
This offloads from #82 the formalization of the configuration for the datagatherers.
It also moves the responsibility of the validation to the data-gatherer package itself. If we finally end up refactoring the whole cmd/check config file parsing to rely on Viper's `mapstructure` annotations, we can make validation errors use the mapstructure tag ([see example](https://stackoverflow.com/questions/40864840/how-to-get-the-json-field-names-of-a-struct-in-golang)).
This is needed to unblock #95, although additional changes might be needed.
> Data gatherers config

- cmd/check.go
- pkg/pathutils/pathutils.go
Move `homeDir` and `expandHome` functions to `pathutils` package for reuse.
> Create pathutils package

- cmd/check.go
- pkg/datagatherer/aks/aks.go
- pkg/datagatherer/datagatherer.go
- pkg/datagatherer/eks/eks.go
- pkg/datagatherer/gke/gke.go
- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/local/local.go
This keeps the spirit of #101 and allows us to create DataGatherers programmatically in #95.
> Use DataGatherer constructors as functions for the config

- cmd/check.go
This PR refactors `cmd.check.go` to separate the decoding of config from the instantiation of items.
It is intended to be a precursor to moving the config loading and decoding out of the main `check` function and using a`Config` stuct.
> Refactor config decoding in check function

- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/k8s/generic_test.go
With this custom unmarshaler, we can parse YAML configuration pretty easily.
See the test file for a configuration example.
> Unmarshaler for k8s data-gatherer configuration

- pkg/datagatherer/k8s/client.go
- pkg/datagatherer/k8s/client_test.go
This allows users to omit the `kubeconfig` field from their config files, instead opting to use their default configured kubeconfig file (as per typical kubectl loading rules).
I've also added a very basic test that exercises these two codepaths. Without breaking out the config loading piece into its own function, this seemed like a nice and quick way to check things work (albeit it *doesn't* validate the the *expected* config file is being loaded, only that one _is_ loaded).
> k8s: allow setting KUBECONFIG to use via environment variable

- pkg/datagatherer/k8s/client.go
Without this, agents running in pods will still look for a kubeconfig
file.
Encountered during: https://github.com/jetstack/preflight/issues/127
> Use non interactive client loading rules

- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/k8s/generic_test.go
This PR changes the Kubernetes data gatherer so that when Secret resources are gathered their data is removed.
Closes #129
> Redact Kubernetes Secret data

- cmd/agent.go
- pkg/agent/run.go
This is convenient in some cases.
For instance, now it is easier to inject an env. variable with `kubectl set env` and user it in as a flag.
> Support providing auth token in cli flag

- pkg/agent/run.go
Enforce the use of auth token.
> Fail if auth token is not present.

- Dockerfile
[Image builds are failing](https://prow.build-infra.jetstack.net/view/gcs/jetstack-logs/logs/post-preflight-release-canary/1240239917678727168) because we were trying to load the legacy config.
This changes the Dockerfile so we default to the agent command and we load the agent config.
> Add agent config instead of old config

- Makefile
- docs/check.md
Follows fix in https://github.com/jetstack/preflight/pull/140
> Fix some missing references to deprecated examples

- cmd/root.go
- go.mod
This binds environment variables to cli flags which makes configuration easier for containers.
> Bind env variables to config flags

- agent.yaml
Use a real token as example and the actual endpoint of the server.
> Use better defaults for config file

- pkg/datagatherer/k8s/generic.go
- pkg/datagatherer/k8s/generic_test.go
This implements https://github.com/jetstack/preflight/issues/155
Turns our that --field-selector in the API does not support set operations like label selectors :cry: I instead make a request for each namespace.
> Scrape only Included namespaces when set to allow more restricted RBAC

- pkg/agent/run.go
We introduced a regression in #159 as we were misconfiguring the preflight client with `"(redacted)"` instead of the actual token.
This contains the fix.
> Fix bug with new preflight client and basic auth

- Makefile
- api/agent.go
- api/datareading.go
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/client/http.go
This adds support for the new form of the endpoint that gathers data.
It introduces significant changes in the configuration, but everything should be backward compatible.
These changes are:
- The `Schedule` field is not optional, as we are using the period flag at the moment.
- The `Token` string is also optional, as it should not be specified when using OAuth2.
- The `Endpoint` is being deprecated, as in the future you won't configure the endpoint for uploading data, just preflight server. At the moment it is still being used if specified, but ignored and defaulting to `/api/v1/datareadings` otherwise.
- Added a new `Server` property that points to the Preflight server. Defaults to `https://preflight.jetstack.io` if not specified.
- Added `OrganizationID` which will be used with the new …
> Make agent support new endpoint for gathering data

- pkg/agent/run.go
We have plans to enable more dgs by default. If these fail, the agent should still attempt to send partial data.
Agent should also refresh data per run and config too to load in any changes in its work.
> Refresh config, data per run (and allow partial data posting)

- Makefile
- pkg/agent/run.go
- pkg/client/accessToken.go
- pkg/client/client.go
- pkg/client/credentials.go
This fixes some issues related to the oauth2 client.
Also, I have moved `Credentials` to the `client` package and now it supports loading `ClientID`, `ClientSecret` and `AuthServerDomain` from the credentials file, which is useful for development.
> Fix some issues for oauth2 client

- docs/datagatherers/k8s-discovery.md
- docs/datagatherers/k8s-dynamic.md
- examples/cert-manager-agent.yaml
- pkg/agent/config.go
- pkg/datagatherer/k8s/client.go
- pkg/datagatherer/k8s/client_test.go
- pkg/datagatherer/k8s/discovery.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
This makes use of the discovery client in client-go to get the server
version information. We need this to use in upcoming packages.
https://godoc.org/k8s.io/client-go/discovery
Sadly, the fake discovery client doesn't seem to work in the same way as
the dynamic one and I've not spent the time to write tests around it.
However, it's operation is much simpler. Open to suggestions on how to
test this in the same way as the dynamic client.
This PR also updates all docs and renames the k8s datagatherer to
k8s-dynamic in a backwards compatible manner.
(Internal Issue: https://github.com/jetstack/preflight-platform/issues/350)
> Implementation of k8s-discovery datagatherer

- pkg/agent/run.go
If the server is not running (e.g. localhost) then we get a stack trace
without this. We should check the error.
Eventually, we can implement a more graceful retry policy.
> Check post data error

- cmd/agent.go
- cmd/helpers.go
- cmd/version.go
Add a `preflight agent info` command that prints some useful debugging information.
Remove the "Experimental" tag for the credentials file, as it is fully supported now.
> Add agent info command

- pkg/client/client.go
I ran into this will the following agent yaml
<details><summary>expand</summary>
<p>
```yaml
schedule: "* * * * *"
token: [redacted]
endpoint:
protocol: https
host: preflight.jetstack.io
path: /api/v1/datareadings
data-gatherers:
- kind: "k8s-dynamic"
name: "k8s/pods"
config:
resource-type:
resource: pods
version: v1
- kind: "k8s-dynamic"
name: "k8s/services.v1"
config:
resource-type:
resource: services
version: v1
- kind: "k8s-dynamic"
name: "k8s/secrets.v1"
config:
resource-type:
version: v1
resource: secrets
- kind: "k8s-dynamic"
name: "k8s/certificates.v1alpha2.cert-manager.io"
config:
resource-type:
group: cert-manager.io
version: v1alpha2
resource: certificates
- kind: "k8s-dynamic"
name: "k8s/ingresses.v1beta1.networking.k8s.io"
config:
resource-type:
group: networking.k8s.io …
```
> Catch missing OAuth2 credentials

- pkg/agent/run.go
Logging the version at the beginning would make it easier debugging of user issues when they paste the logs.
> Log version to make debugging easier

- agent.yaml
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
This feature was implemented but was not connected to the config file -
oops, my bad!
This also updated the default token to match the one used in the backend for the dummy org.
> Set included namespaces as loaded from config

- agent.yaml
- cmd/agent.go
- pkg/agent/run.go
Number of periods is integer.
Takes -1 as default (runs perpetually) - Any -ve will do this
> Add flag for number periods gathering/posting data

- cmd/agent.go
- pkg/agent/run.go
Flag --write-to-file allows for a local path to be given to which data is stored.
Only stores data locally if no organization is specified. - This can be added for when organisation is specified if needed.
Signed-off-by: Jamie Leppard <JammyL@users.noreply.github.com>
> Adds write-to-file flag to store data locally

- cmd/agent.go
- pkg/agent/run.go
Allows for an input file to be specified. 
This replaces the data collected by data gatherers from clusters.
> Flag: input-path

- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
This adds two fields to the agent.yaml to specify the input and output path instead of using the flag.
> Input/Output Path added to agent.yaml

- Makefile
This makes changes the way the binary is compiled, so it is statically linked.
This is good so we eliminate some system dependencies that weren't present on some basic images.
> Use static linking

- pkg/agent/run.go
The error formatting would run even with a nil error
leading to a seg fault.
This now only runs if an error is present.
The return has also been corrected to stop the exp-backoff
always running
Signed-off-by: Jamie Leppard <JammyL@users.noreply.github.com>
> exp backoff fails when datagatherers have no error

- cmd/agent.go
- pkg/agent/run.go
The exponential backoff algorithm causes svc accountsto be blocked after 11 login attempts.
To stop the accounts being blocked on a single set of login attempts the backoff algorithm has beenslowed down.
At this stage, I am still unsure of the time limit over which these 11 attempts will block an account.
This means that multiple retries of the end-to-end step in the CI pipeline may still block a svc account.
Signed-off-by: Jamie Leppard <JammyL@users.noreply.github.com>
> Increased backoff time for repeated login attempts

- cmd/agent.go
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/client/http.go
Removes basic auth from the preflight client inialization.
Still allows preflight client to be not auth.
Related #414
Signed-off-by: Oluwole Fadeyi <tfadeyi@users.noreply.github.com>
> Remove basic auth from agent codebase

- cmd/agent.go
- pkg/agent/run.go
- pkg/datagatherer/error/error.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/local/local.go
Agent will hard fail if a data gatherer is defined for a missing CRD.
Related [#510](https://github.com/jetstack/preflight-platform/issues/510)
> Add strict flag to agent

- api/agent.go
- api/datareading.go
- pkg/agent/run.go
- pkg/client/client.go
This will allow agent data to be categorized and stored in preparation
for processing async on the backend.
> Send gather time and cluster ID in agent upload

- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
I appear to have made an error in https://github.com/jetstack/preflight/pull/152.
It is looking for field annotations on objects which is never set,
annotation are nested under metadata.
> Remove last-applied... annotation from metadata

- go.mod
- go.sum
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
- pkg/datagatherer/k8s/fieldfilter.go
- pkg/datagatherer/k8s/fieldfilter_test.go
This can also be imported by the backend.
Also changes uploaded secret data to only contain a fixed allowlist of keys within the object.
> Implement more generic means of filtering uploaded objects

- pkg/datagatherer/k8s/fieldfilter.go
- pkg/datagatherer/k8s/fieldfilter_test.go
This isn't essential since we're now selecting fields but it should
still be fixed.
> Correct last-applied-configuration annotations key

- go.mod
- go.sum
- pkg/agent/run.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/fieldfilter.go
This will only make a difference for non-secret resources. Secret
resources lose this annotation via selection.
Also use the Redact fields package var
> Correct JSONPointer for redacting last-applied

- go.mod
- go.sum
- pkg/datagatherer/versionchecker/fixtures/manifest-100.json
- pkg/datagatherer/versionchecker/fixtures/manifest-101.json
- pkg/datagatherer/versionchecker/fixtures/nodes.json
- pkg/datagatherer/versionchecker/fixtures/pods.json.tmpl
- pkg/datagatherer/versionchecker/versionchecker.go
- pkg/datagatherer/versionchecker/versionchecker_test.go
Updating version checker data gatherer to support multi-arch images.
This PR uses the packages from the https://github.com/jetstack/version-checker/tree/58-add-arch-and-os-checks
branch of version-checker.
With this change checks will be performed on the image for the correct architecture, so if node is amd64 the check is done on images with amd64. This won't fix the issues seen with fat manifests [#58](https://github.com/jetstack/version-checker/issues/58).
Signed-off-by: oluwole.fadeyi <oluwole.fadeyi@jetstack.io>
> Update version checker data gatherer

- Makefile
We are transitioning to a new domain for the auth server. This configures the new domain in the agent binary.
We are going to be backward compatible, so old agents can run with the old domain.
> Use new auth server domain

- agent.yaml
The default config was not valid as it was using an old format. These changes make it valid.
> Change default config to be valid

- pkg/datagatherer/versionchecker/versionchecker_test.go
We are using this since we don't support the injecting of a fake client.
This is a difference with the dynamic dg I feel is worth highlighting.
> Explain use of localServer in version checker dg

- pkg/datagatherer/istio/gvrs.go
This didn't look right, think there's a typo in the `workloadentries` definition.
> Fix up istio workloadentries CRD

- api/datareading.go
- api/datareading_test.go
- go.mod
- go.sum
- pkg/agent/dummy_data_gatherer.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/datagatherer/aks/aks.go
- pkg/datagatherer/datagatherer.go
- pkg/datagatherer/eks/eks.go
- pkg/datagatherer/gke/gke.go
- pkg/datagatherer/istio/istio.go
- pkg/datagatherer/istio/istio_test.go
- pkg/datagatherer/k8s/cache.go
- pkg/datagatherer/k8s/cache_test.go
- pkg/datagatherer/k8s/discovery.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
- pkg/datagatherer/local/local.go
- pkg/datagatherer/versionchecker/versionchecker.go
- pkg/datagatherer/versionchecker/versionchecker_test.go
Replaces #221
We are planning to use informers rather than polling the API to allow us to gather data about resources which live for less than a minute before polling intervals.
**Original Body:**
<details>
<summary><b>Missing resources</b></summary>
```
2021/03/19 17:22:55 No credentials file was specified. Starting client with no authentication...
2021/03/19 17:22:56 failed to start and cache sync "k8s-dynamic" data gatherer "k8s/certificates": timed out waiting for caches to sync
2021/03/19 17:22:56 failed to start and cache sync "k8s-dynamic" data gatherer "k8s/certificaterequests": timed out waiting for caches to sync
2021/03/19 17:22:56 Successfully gathered data for "k8s/pods"
2021/03/19 17:22:56 Successfully gathered data for "k8s/secrets"
2021/03/19 17:22:56 Successfully gathered …
```
> Use informers for dynamic datagatherers

- .github/workflows/release-master.yml
- .github/workflows/release-tag.yml
- .github/workflows/test.yml
Suggested fix when hitting the 401 authorized error that we are when trying to push new images:
https://github.com/docker/buildx/issues/327
Signed-off-by: David Bond <davidsbond93@gmail.com>
> Use moby/buildkit:master when setting up buildx

- Dockerfile
We're running issues getting the agent to work out of the box on OpenShift clusters due to the
way they set up security contexts. We're trying to align our Docker image with cert-manager's
as their deployments work out of the box with the restrictions that OpenShifts's SecurityContextConstraints
custom resource applies by default.
Signed-off-by: David Bond <davidsbond93@gmail.com>
> Use USER 1000:1000 in agent image.

- Dockerfile
The initial switch to USER 1000:1000 didn't seem to solve the problem, going to try
using the same base image that cert-manager does also.
Signed-off-by: David Bond <davidsbond93@gmail.com>
> Switch to distroless/static base image

- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/permissions/generate.go
- pkg/permissions/generate_test.go
Made a string of RBAC from GVRs.
#250
> Rbac generate

- pkg/agent/config.go
- pkg/permissions/generate.go
- pkg/permissions/generate_test.go
Create RBAC struct from GVRs
#250
> Rbac struct 2

- builder.dockerfile
- go.mod
- go.sum
Updating the agent to use golang version 1.16 rather than 1.13.
Allows us to use new golang features, like embedded files
Signed-off-by: oluwole.fadeyi <oluwole.fadeyi@jetstack.io>
> Update golang to 1.16

- pkg/datagatherer/k8s/dynamic_test.go
- pkg/datagatherer/k8s/fieldfilter.go
To allow users to filter out system certificates, we need to check their annotations. Currently, the agent does not send these.
This commit modifies the agent to provide annotations in the request to the backend
> Send secret annotations to platform

- pkg/agent/run.go
This fixes three dropped `err` variables in `pkg/agent`.
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
> pkg/agent: fix dropped errors

- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/fieldfilter.go
- pkg/datagatherer/k8s/fieldfilter_test.go
This PR is to exclude sensitive fields from OpenShift Route resources.
It is likely further changes are required before the PR can be approved & merged.
Two of the main issues I can think of are:
1. I was not able to establish with absolute certainty what fields the **Route** resource has and which of these we want to keep. If the [defined fields](https://github.com/jetstack/jetstack-secure/blob/2605a7512be45e3b3007c48686e9866ce9953052/pkg/datagatherer/k8s/fieldfilter.go#L28-L46) are not correct, further changes are required. [This](https://docs.openshift.com/container-platform/4.8/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration) (see the _YAML Definition of an autogenerated route_) so far is the most relevant OpenShift …
> Open shift route filter

- .github/workflows/release-master.yml
- .gitignore
- Makefile
- README.md
- docs/guides/cosign/guide.md
Signs the agent container image with cosign's keyless signing and Github OIDC. Also signs and attaches a SLSA provenance attestation and a CycloneDX SBOM.
The provenance provided takes the agent up to SLSA 1.
The signatures and other attachments are stored in a separate repository to the actual container images. There are two main reasons for this:
1. Although quay.io supports cosign signatures as of the latest release, it doesn't support uploading attestations or SBOMs.
2. Pulling SBOMs, attestations and signatures for verification can skew image pull metrics for the repository. The number of pulls strikes me as something we might want to track reliably for the agent.
> Add signing, provenance and SBOM

- cmd/agent.go
- pkg/agent/run.go
This adds a pprof server running on 6060 to aid in investigating memory
usage of the agents. This can be eneabled or disable through a flag
`profiling`
Signed-off-by: oluwole.fadeyi <oluwole.fadeyi@jetstack.io>
> Add pprof profiling endpoints to the agent

- pkg/datagatherer/k8s/fieldfilter_test.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes five dropped `err` variables in `pkg/datagatherer/k8s`.
> pkg/datagatherer/k8s: fix dropped test errors

- cmd/agent.go
- go.mod
- pkg/agent/run.go
This PR adds a prometheus server to agent hidden behind the
enable-metrics flag on port 8081. This is used for debugging purposes.
Signed-off-by: oluwole.fadeyi <oluwole.fadeyi@jetstack.io>
> Add prometheus server

- go.mod
- go.sum
- pkg/agent/run.go
- pkg/datagatherer/k8s/fieldfilter.go
Currently the Agent running on larger clusters, i.e: Openshift, or clusters with many thousands of resources seem to be use quite a bit of memory hitting the current memory limits (200M) and might get OOM killed.
In order to reduce the memory usage we are going substitute golang json encoder library with https://github.com/json-iterator/go, from pprof we can both Marshalling and Unmarshalling hug much of the cumulative memory.
**PPROF profile  (vanilla agent)**
**Prometheus inuse memory (vanilla agent)**
The average memory use seems to be ~ 170 MB for a vanilla agent in an Openshift cluster.
```
kubectl get pod --all-namespaces | wc -l
334
kubectl get secrets --all-namespaces | wc -l
1619
kubectl get statefulsets.apps --all-namespaces | wc -l
5
kubectl get deployments.apps …
```
> Replace json/encoder with jsoniter

- Dockerfile
- builder.dockerfile
Using [go-licenses](https://github.com/google/go-licenses) to pull in the licensing for all go dependencies. The release image then hosts all licencing information under: "/usr/share/doc/preflight".
Tried to implement in a manner that fitted best with the Makefile / Dockerfile hybrid solution going on.
Thanks to @JamesLaverack for going through this with me. After building locally we extracted the image and inspected the contents, here's an example output for reference:
```
usr/
usr/share/
usr/share/doc/
usr/share/doc/preflight/
usr/share/doc/preflight/cloud.google.com/
usr/share/doc/preflight/cloud.google.com/go/
usr/share/doc/preflight/cloud.google.com/go/compute/
usr/share/doc/preflight/cloud.google.com/go/compute/metadata/
usr/share/doc/preflight/cloud.google.com/go/compute/metadata/LI …
```
> feat: Adding licensing information to image

- pkg/datagatherer/k8s/cache.go
- pkg/datagatherer/k8s/client.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
- pkg/datagatherer/versionchecker/fixtures/nodes.json
- pkg/datagatherer/versionchecker/fixtures/pods.json.tmpl
- pkg/datagatherer/versionchecker/versionchecker.go
- pkg/datagatherer/versionchecker/versionchecker_test.go
The k8s/dynamic is now going to use a sharedinformer for k8s native
v1 resources, instead of using a dynamicinformer. This reduceses the
current memory usage by about 25MB.
Before the refactoring, the memory usage was around ~117MB https://github.com/jetstack/jetstack-secure/pull/306
**After refactoring** the average memory usage is ~92MB
**After refactoring profiling**
Signed-off-by: Oluwole Fadeyi <oluwole.fadeyi@jetstack.io>
> Refactor k8d/dynamic datagatherer

- .github/workflows/release-master.yml
- .github/workflows/test.yml
This should allow the CI docker image build step to proceed.
Signed-off-by: Oluwole Fadeyi <oluwole.fadeyi@jetstack.io>
> Add github action workaround

- README.md
- pkg/agent/metrics.go
- pkg/agent/run.go
Adds a prom gauge metrics for the datareadings upload size.
Signed-off-by: Oluwole Fadeyi <oluwole.fadeyi@jetstack.io>
> Add datareadings size prom metrics

- Makefile
The new versions of cosign ask for confirmation and requires `-y` for unattended installations.
> Auto confirm cosign

- pkg/client/client.go
- pkg/client/client_oauth.go
When OAuth authentication was introduced, some of the code was added to `client.go`. Since those changes only apply to OAuth rather than all clients, this PR moves the code from `client.go` to `client_oauth.go`.
> Move oauth client code into client_oauth.go

- examples/cert-manager-agent.yaml
Without these fields I get the following error when trying to use the example:
```console
$ go run ./ agent --one-shot --output-path ./output  --agent-config-file examples/cert-manager-agent.yaml
2023/06/09 13:12:23 Preflight agent version: development ()
2023/06/09 13:12:23 Failed to parse config file: 2 errors occurred:
* organization_id is required
* cluster_id is required
exit status 1
```
After adding these fields, the one-shot discovery works:
```console
$ go run ./ agent --one-shot --output-path ./output  --agent-config-file examples/cert-manager-agent.yaml
2023/06/09 13:12:33 Preflight agent version: development ()
2023/06/09 13:12:33 Using deprecated Endpoint configuration. User Server instead.
2023/06/09 13:12:33 Loaded config:
schedule: '* * * *'
period: 0s
endpoint:
protocol: …
```
> Add missing required fields to cert-manager example

- agent.yaml
- cmd/agent.go
- go.mod
- go.sum
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/client/client_oauth.go
- pkg/client/client_tls_protect_cloud.go
- pkg/client/client_venafi_cloud.go
This PR adds the ability to add authentication for TLS Protect Cloud to the agent for uploading cluster information. A new flag is introduced to pass a new type of credentials file.
> TLS Protect Cloud Authentication Addition

- cmd/agent.go
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
- pkg/client/client_venafi_cloud.go
These changes solidify the way users configure the agent to communicate to venafi-cloud. It allows the agent to set the `--venafi-cloud` without having to define 
```yaml
venafi-cloud:
uploader_id: ""
upload_path: ""
```
in the `config.yaml`.
The yaml configuration can still be used for a non default agent setup. It will override the default `uploader_id` and `upload_path`.
> Refactor the venafi-cloud configuration

- pkg/agent/config.go
- pkg/agent/run.go
This allows the server URL to be specified in the agent.yaml even when `--venafi-cloud` flag is present.
> Allow server to be configured with `--venafi-cloud`

- cmd/agent.go
- pkg/agent/run.go
This will help simplify #466.
This changes make it possible to use `--client-id` to specify the client ID (and optionally `--private-key-path`) when using the Venafi Cloud authentication, allowing the user to not need to provide a `credentials.json` file.
This change should be backwards compatible.
> Allow to use ClientID and PrivateKeyPath as flags instead of credentials.json file

- .github/workflows/release-master.yml
This PR duplicates the release related steps to also push a `venafi-agent` container image.
> Feat: Duplicate release steps for 'venafi-agent' Docker image

- deploy/charts/jetstack-agent/Chart.yaml
- deploy/charts/jetstack-agent/README.md
- deploy/charts/jetstack-agent/tests/__snapshot__/configuration_test.yaml.snap
- deploy/charts/jetstack-agent/values.yaml
Using the latest `jetstack-agent` chart it showed as out of date by the platform.
This fixes that.
> chore: Update agent version to latest

- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
This PR implements [VC-30108](https://venafi.atlassian.net/browse/VC-30108) by updating the tlspk agent configuration to gather and update firefly.
Related to MR [#168](https://gitlab.com/venafi/vaas/applications/tls-protect-for-k8s/venctl/-/merge_requests/168/edit)
[VC-30108]: https://venafi.atlassian.net/browse/VC-30108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update agent config to upload firefly

- go.mod
- go.sum
- pkg/agent/config.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_unauthenticated.go
- pkg/client/client_venafi_cloud.go
Allows the user to configure a cluster description to be used during the cluster registration in the Venafi control plane.
**Changes:**
* Add `cluster_description` to the agent configuration.
* Update the client interface and concrete structs to support `PostDataReadingsWithOptions`.
> feat(client): Allow agent to send cluster description

- deploy/charts/venafi-kubernetes-agent/Chart.yaml
- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
- deploy/charts/venafi-kubernetes-agent/values.yaml
Adds cluster onboarding values to the agent helm chart.
Change:
* Add onboarding object to the values.yaml
* Add onboarding.clusterName which updates the agent configMap template 
* Add onboarding.clusterDescription which updates the agent configMap template
* Update Autogen docs
**Note**: Wait until v0.1.44 agent is released before merging
> feat(onboarding): Add onboarding values to the helm chart

- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/templates/poddisruptionbudget.yaml
- deploy/charts/venafi-kubernetes-agent/values.yaml
This brings the agent into line with many other open source charts (see e.g. cert-manager).
We document this as a best practice here:
https://docs.venafi.cloud/vaas/k8s-components/c-k8s-components-best-practice/#poddisruptionbudget
This is largely adapted from https://github.com/cert-manager/trust-manager/tree/main/deploy/charts/trust-manager !
> feat(helm): Add PodDisruptionBudget option to helm chart

- deploy/charts/venafi-kubernetes-agent/tests/deployment_test.yaml
- deploy/charts/venafi-kubernetes-agent/values.yaml
Update the venafi-agent chart to use the image in the venafi public repository
> Use agent image in the venafi repository

- deploy/charts/venafi-kubernetes-agent/templates/rbac.yaml
This seems like a clear oversight since everything else in this file has these labels included!
> Add missing labels for VEI clusterrole / binding

- deploy/charts/jetstack-agent/templates/configmap.yaml
- deploy/charts/jetstack-agent/templates/deployment.yaml
- deploy/charts/jetstack-agent/templates/secret.yaml
- deploy/charts/jetstack-agent/templates/serviceaccount.yaml
- deploy/charts/jetstack-agent/tests/__snapshot__/configuration_test.yaml.snap
- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
- deploy/charts/venafi-kubernetes-agent/templates/deployment.yaml
- deploy/charts/venafi-kubernetes-agent/templates/serviceaccount.yaml
Source: https://venafi.atlassian.net/browse/VC-32006
When installing with `helm install`, the namespace doesn't need to be present on the templates. Helm automatically installs the resources that don't have a specific namespace to the namespace specified in `--namespace`.
But when using `helm template`, the resulting templated manifests don't contain a namespace, even though `--namespace` was used. This is an old issue of Helm (https://github.com/helm/helm/issues/3553). And since a lot of people rely on `helm template` and then feed that into ArgoCD, it makes to add the `namespace` field to all namespaced resources.
Thus, this PR adds the `namespace` in the configmap, deployment, and serviceaccount templates.
Manual test **for the chart `venafi-kubernetes-agent`**:
```bash
git checkout …
```
> Helm: the namespace was missing in the configmap, deployment, and serviceaccount templates

- pkg/agent/dummy_data_gatherer.go
- pkg/agent/run.go
- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_unauthenticated.go
- pkg/client/client_venafi_cloud.go
- pkg/datagatherer/datagatherer.go
- pkg/datagatherer/k8s/client.go
- pkg/datagatherer/k8s/discovery.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
- pkg/datagatherer/local/local.go
The current logs are somewhat confusing, and missing some very useful information. This is an attempt
to clean it up in a few ways:
*  Log the number of items from each dg. Each datagatherer can return 
the number of items it collected so that the logs tell us a bit more about
what was found in the cluster, and can help find where any items have
been missed.
* Log a more informative error message when giving up on uploading
readings to the server. This would be the last message before
the pod exits, so if the pod ends up in CrashLoopBackoff it's
important to highlight this as the reason.
* Remove the "Running Agent" log message, it's not clear what it means
* Put [] around the body as if the body is empty the log message
can read like the following message is the body.
```
2024/05/10 …
```
> fix(log): Some improvements to the logs

- deploy/charts/jetstack-agent/README.md
- deploy/charts/jetstack-agent/templates/deployment.yaml
- deploy/charts/jetstack-agent/tests/deployment_test.yaml
- deploy/charts/jetstack-agent/tests/values/custom-volumes.yaml
- deploy/charts/jetstack-agent/values.yaml
I was working with a customer and needed to pass a configmap mount to the deployment.
This is not currently available in the chart.
This PR adds this capability in a generic way, similar to how it is done in the [cert-manager chart](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L317-L321).
I have specifically not created a new release of the chart. I intend to do a simple followup PR to release 0.3.2.
> feat: enable volumes and volumeMounts to be passed to the jetstack-agent deployment

- deploy/charts/venafi-kubernetes-agent/templates/deployment.yaml
- deploy/charts/venafi-kubernetes-agent/tests/deployment_test.yaml
- deploy/charts/venafi-kubernetes-agent/tests/values/custom-volumes.yaml
- deploy/charts/venafi-kubernetes-agent/values.yaml
Ref: https://venafi.atlassian.net/browse/VC-34488
We found that there is currently no “knob” in the Venafi Kubernetes Agent `values.yaml` file to configure a custom CA bundle. @hawksight created a GitHub issue for that: #541.
In this PR, I add the new `volumes` and `volumeMounts` and added examples of how to set up a custom CA bundle in the comments of the CA bundle. 99% of this PR comes from @hawksight's work in #540.
The way I intend users to use custom CA bundles is to first create a config map:
```bash
kubectl create configmap cabundle -n venafi \
--from-file=cabundle=./your/custom/ca/bundle
```
Then, the user configures its `values.yaml` with the following:
```yaml
volumes:
- name: cabundle
configMap:
name: cabundle
defaultMode: 0644
volumeMounts:
- name: cabundle
mountPath: …
```
> VC-34488: Add `volumes` and `volumeMounts` for using custom CA bundles in the Venafi Kubernetes Agent

- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/values.yaml
In https://docs.venafi.cloud/vaas/k8s-components/c-k8s-components-best-practice/#cpu we say:
> Read [Stop Using CPU Limits on Kubernetes](https://home.robusta.dev/blog/stop-using-cpu-limits), to learn why the best practice is to set CPU requests, but not limits.
So I've removed the default CPU limit from the chart values for venafi-kubernetes-agent.
I have not changed the `jetstack-agent` charts, because I think it is now considered legacy.
I also removed the note about using vertical pod autoscaler, because it seems irrelevant. We don't mention VPA in the documentation or in the other charts AFAIK.
> [VC-32659] Remove the default CPU limit

- README.md
- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/templates/deployment.yaml
- deploy/charts/venafi-kubernetes-agent/templates/podmonitor.yaml
- deploy/charts/venafi-kubernetes-agent/values.yaml
In https://github.com/jetstack/jetstack-secure/pull/341 @tfadeyi added a metrics server to the agent.
In this PR I've made the minimum viable changes to allow that metrics server to be queried by Prometheus,
when the agent is installed by Helm in a Kubernetes cluster.
* I have chosen to only update the venafi-kubernetes-agent chart, because I believe the jetstack-secure agent is deprecated / retired.
* I decided not to make the metrics server port configurable. In csi-driver and approver-policy etc it is configurable, to allow users to change it in case it clashes with some other sidecar container that might be injected in the pod. If it becomes necessary, we can make the port configurable in a followup PR.
* I decided not to add any E2E tests...because there weren't any existing tests to …
> [VC-34401] Add metrics settings to the Helm chart

- deploy/charts/venafi-kubernetes-agent/values.yaml
This also fixes an issue in OpenShift where OpenShift wants you to use a certain range of UIDs that 1000 does not fall into:
```
.containers[0].runAsUser: Invalid value: 1000: must be in the ranges: [1000660000, 1000669999]
```
By not specifying an runAsUser in the yaml, OpenShift picks a appropriate UID for you:
```
$ kubectl get deployment venafi-kubernetes-agent | grep runAsUser
$ kubectl get pod venafi-kubernetes-agent-6b8f756ffb-rmb45 -o yaml | grep runAsUser
runAsUser: 1000660000
```
Since the Dockerfile contains the USER directive this should have no effect on non OpenShift Kubernetes clusters.
> fix: runAsUser in yaml is unneeded as its set in the Dockerfile

- README.md
I've also re-structured the README so that everything that talks about tiers is its own section. It should be much clearer now to what images and helm charts each customer has access to.
> readme: remember to edit the github release before publishing

- cmd/agent.go
- pkg/agent/run.go
- pkg/datagatherer/k8s/cache.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/echo/echo.go
- pkg/logs/logs.go
Ref: [VC-35375](https://venafi.atlassian.net/browse/VC-35375 "AGENT: Fix the logs that say VCert...")
This prevents issues caused by external libraries which reconfigure the standard logger.
For example, in https://github.com/jetstack/jetstack-secure/pull/552, we saw that all log messages were prefixed with "vCert: ".
[VC-35375]: https://venafi.atlassian.net/browse/VC-35375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use our own logger instance instead of the standard logger

- .github/workflows/release-master.yml
- pkg/agent/run.go
- pkg/client/client_venconn_test.go
- pkg/datagatherer/k8s/client.go
- pkg/kubeconfig/kubeconfig.go
This is a follow-up PR to #552. I had forgotten to push these few commits before clicking "Merge"... 😨
- The first commit fixes a few `log` that should have been `logs.Log`.
- The second is about the tests: it moves the Go objects to inline YAML manifests for the RBAC and Secrets objects with the aim of making the tests a little more readable as well as making the task of comparing the inline YAML with the Helm chart easier.
- The third commit deduplicates the `loadRESTConfig` func (suggested in Richard's [comment](https://github.com/jetstack/jetstack-secure/pull/552#discussion_r1727089923)).
- Fourth commit fixes the CI on the master branch. CI is failing with "`/bin/sh: git: not found`". The issue is that `git` is missing when the GitHub Action "ssh-agent" runs. Example of failure: …
> Feedback from #552

- pkg/client/client_venconn_test.go
Sometimes (for example when the CRD file isn't found), the test would stop immediately after envtest.Start, meaning that the t.Cleanup block wouldn't run and the two new processes would be left over after the test process would end.
Credit for identifying this bug and fixing goes to Richard Wall in ([1]).
[1]: https://github.com/jetstack/jetstack-secure/pull/560#issuecomment-2306678780
> Leftover processes after running `make test`

- cmd/agent.go
- go.mod
- go.sum
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
Stacked on top of https://github.com/jetstack/jetstack-secure/pull/564.
Ref: [VC-35630](https://venafi.atlassian.net/browse/VC-35630)
I found that almost none of the "config/flags" code is tested, which made me wary of changing the code without adding more tests. And since I'll have to change this code again for [VC-35630](https://venafi.atlassian.net/browse/VC-35630), I'd prefer writing some unit tests first.
This PR aims to change no actual logic. The changes you see are the refactoring I had to do to be able to unit test how configuration is loaded.
[VC-35630]: https://venafi.atlassian.net/browse/VC-35630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VC-35630]: https://venafi.atlassian.net/browse/VC-35630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
> VC-35630: Add unit tests to the code that loads config/flags

- cmd/agent.go
- go.mod
- go.sum
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
I propose to remove code that "dumps" the config file at startup.
I don't think there is a point in dumping the whole content of a file... it's super verbose and not very useful. It should at least be gated behind a `--debug` flag. So I propose to remove it for now. Let me know if you prefer that I move this specific change to another PR.
This partially fixes [VC-33564](https://venafi.atlassian.net/browse/VC-33564 "AGENT: Important logs are drown in a sea of server missing resource for datagatherer").
[VC-33564]: https://venafi.atlassian.net/browse/VC-33564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VC-33564: Disable the dump of the config file on startup

- hack/e2e/application-team-1.yaml
- hack/e2e/test.sh
- hack/e2e/values.venafi-kubernetes-agent.yaml
- hack/e2e/venafi-components.yaml
This modified script will create a GKE cluster and set up: venafi-enhanced-issuer, approver-policy-enterprise, and venafi-kubernetes-agent to authenticate to Venafi Control Plane using a Kubernetes ServiceAccount Token.
```console
$ ./hack/e2e/test.sh
...
2024/08/23 16:35:02 Venafi Connection mode was specified, using Venafi Connection authentication.
2024/08/23 16:35:02 ignoring venafi-cloud.upload_path. In Venafi Connection mode, this field is not needed.
2024/08/23 16:35:02 ignoring venafi-cloud.uploader_id. In Venafi Connection mode, this field is not needed.
2024/08/23 16:35:02 Prometheus was enabled.
Running prometheus server on port :8081
2024/08/23 16:36:13 Posting data to: https://api.venafi.cloud/
2024/08/23 16:36:13 retrying in 20.592925933s after error: post to server failed: …
```
> Test secretless authentication on GKE

- README.md
- deploy/charts/venafi-kubernetes-agent/Chart.yaml
This commit belongs to the release process for v1.0.0.
I've removed an instruction from the release process as I've noticed that the `tag` is now commented out in the values.yaml file:
```yaml
image:
```
> Helm: bump version to 1.0.0 and appVersion to v1.0.0

- go.mod
- go.sum
- pkg/client/client_oauth.go
`github.com/pkg/errors` is used in the rest of the project and does not have a LGPL license
> Replace github.com/juju/errors with github.com/pkg/errors

- cmd/agent.go
- pkg/agent/run.go
- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_unauthenticated.go
- pkg/datagatherer/k8s/client_test.go
- pkg/datagatherer/local/local.go
`io/ioutil` has been deprecated for a long time.
> Replace deprecated ioutil package

- .golangci.yaml
Removes linters without violations from the "exclude-rules" list.
> Remove unnecessary linter exceptions

- deploy/charts/venafi-kubernetes-agent/templates/deployment.yaml
- pkg/agent/run.go
Ref: [VC-36444](https://venafi.atlassian.net/browse/VC-36444 "AGENT: Expose health checks (probes)")
**Why?** Customers don’t like the fact that OpenShift shows warnings whenever they install Venafi Kubernetes Agent. These warnings say that this pod doesn’t have a liveness and a readiness configuration in the Pod specification, and that the best practice is to have one for each pod.
**What?** The idea isn’t to define what “ready” means in the agent. The agent doesn’t receive traffic, so it wouldn’t make sense to configure a readiness probe (readiness probes are used by Kubernetes to know when to start routing traffic to that pod). And regarding the liveness probe, although it could be useful to indicate that the agent isn’t able to push data to the API, defining a “real” liveness probe is …
> VC-36444: Add a health check and liveness probe

- pkg/datagatherer/k8s/fieldfilter.go
- pkg/datagatherer/k8s/fieldfilter_test.go
- pkg/testutil/undent.go
- pkg/testutil/undent_test.go
Ref: [VC-36545](https://venafi.atlassian.net/browse/VC-36545 "Update the agent to collect labels from secrets")
This PR makes sure labels are being pushed for Secret resources.
**Note to the reviewer:** I took the liberty of rewriting the tests. The best approach would have been to write a minimal commit with the feature and test changes, and then refactor the tests... but since Olu would prefer this being shipped as part of 1.1.0, I chose not to bother trying to separate the changes from the test refactoring.
The unit tests cover the changes, so I haven't proceeded with manual e2e tests.
[VC-36545]: https://venafi.atlassian.net/browse/VC-36545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VC-36545: Collect the secret's labels

- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
Ref: [VC-36351](https://venafi.atlassian.net/browse/VC-36351 "Update the agent configuration to collect k8s namespace resources")
This PR adds namespaces to the "dynamic" configuration of the Agent in the Helm chart.
There is no automated test for this change. Thus, I went ahead and manually tested the feature.
I've used the tenant https://ven-tlspk.venafi.cloud/. To access the API key, use the user `system.admin@tlspk.qa.venafi.io` and the password is visible in the page [Production Accounts](https://venafi.atlassian.net/wiki/spaces/CT/pages/2115404149) (private to Venafi). Then go to the settings and find the API key.
```sh
export APIKEY=...
```
I've then deployed the agent to a Kind cluster (create it first):
```sh
venctl iam service-account agent create --name "$USER temp" \ …
```
> VC-36351: Include namespaces as part of the resources to be collected

- README.md
- deploy/charts/venafi-kubernetes-agent/Chart.yaml
As specified in the README's release process. I've also updated the README since it was vastly outdated; I've added how things will work once @inteon's changes ([Harbor](https://gitlab.com/venafi/vaas/delivery/harbor/-/merge_requests/48/diffs) and [Enterprise Builds](https://github.com/jetstack/enterprise-builds/pull/222)) will have gone through.
> [Release v1.1.0-alpha.0] Bump Helm chart version to 1.1.0-alpha.0

- README.md
As mentioned earlier today, I forgot to update the release process with the latest changes: we no longer need to create a GitHub Release. We now have to push a tag and wait for the GitHub Release to appear.
> README: Release process: push git tag before editing the release

- make/00_mod.mk
While testing the alpha in https://github.com/jetstack/jetstack-secure/issues/586, I found that the appVersion is missing the `v` prefix. Weirdly enough, the image in the templated deployment had the the `v` prefix...
This PR is fixing `appVersion`.
```console
$ make helm-chart
$ helm show chart _bin/scratch/image/venafi-kubernetes-agent-1.1.0-6-gd18bbc5def3d17-dirty.tgz | grep -i version                                       
appVersion: v1.1.0-6-gd18bbc5def3d17-dirty
version: 1.1.0-6-gd18bbc5def3d17-dirty
```
> VC-36353: Helm: appVersion was missing the v prefix

- hack/e2e/test.sh
- make/02_mod.mk
```console
$ make help
...
Testing
test-unit                     > Unit tests
test-e2e-gke                  > Run a basic E2E test on a GKE cluster
Build and install venafi-kubernetes-agent for VenafiConnection based authentication.
Wait for it to log a message indicating successful data upload.
See `hack/e2e/test.sh` for the full test script.
```
```bash
make test-e2e-gke
```
```console
...
2024/10/10 16:40:49 retrying in 33.032458396s after error: post to server failed: while loading the VenafiConnection venafi/venafi-components: connection is not ready yet (building connection failed): chain element 1 (VCPOAuth) error: Post "https://api.venafi.eu/v1/oauth2/v2.0/9a0cab61-2b00-11ee-ba09-0733b0fe5adc/token": dial tcp: lookup api.venafi.eu on 34.118.224.10:53: read udp …
```
> [VC-35738] Update the E2E test script to use the makefile-modules build targets

- deploy/charts/venafi-kubernetes-agent/templates/deployment.yaml
- deploy/charts/venafi-kubernetes-agent/templates/rbac.yaml
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
Ref: [VC-35568](https://venafi.atlassian.net/browse/VC-35568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ "AGENT: Show a warning in the Pod's events when the Venafi Connection isn't present in the cluster")
This feature aims at giving the user another way of knowing when the Agent isn't sending data to the VCP API. With this PR, the user will have two ways of noticing that the Agent isn't properly working:
- By looking at the logs (but hard since the logs are overwhelming (cf. [VC-33564](https://venafi.atlassian.net/browse/VC-33564 "AGENT: Important logs are drown in a sea of server missing resource for datagatherer")),
- By looking at the Kubernetes events on the Agent pod.
**POSSIBLE BREAKING CHANGE 1:** Previously, `--install-namespace` …
> VC-35568: Feature: Send errors to the pod's event to increase visibility

- go.mod
- go.sum
- pkg/datagatherer/k8s/fieldfilter.go
- pkg/datagatherer/k8s/fieldfilter_test.go
Instead of using the `gabs` library and an unnecessary marshal + unmarshal roundtrip, we can just use the `unstructured` helpers.
This is the first step in the plan outlined here: https://venafi.atlassian.net/browse/VC-36216?focusedCommentId=439503
> VC-36547: Remove gabs library as a dependency

- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/client/client_venafi_cloud.go
- pkg/client/client_venconn.go
- pkg/client/client_venconn_test.go
> VC-36510: Key Pair and Venafi Connection modes now use gzip compression

- pkg/agent/config.go
- pkg/agent/run.go
The pprof server was being started on a second HTTP server running in an unmanaged Go routine.
It used log.Fatal on exit to bring down the process in the event of an error in that server.
Moving the pprof endpoints to the main HTTP server simplifies the code because it avoids having to manage a second server.
It will make it easier to enable TLS on these endpoints in future, if that is desired, because only a single TLS certificate will be required.
It makes life easier for platform admins who will have one less TCP port to worry about.
It removes one more instance of `log.Fatal`, which are scattered all over the run command and moves us closer to removing the use of the legacy `log` module and handling all sub-command errors in a consistent way.
These changes have been extracted from a …
> [VC-35738] Move the pprof endpoints to the main HTTP server rather than starting a second server

- pkg/agent/run.go
This is part of the effort to remove the use of the legacy `log` module and replace it with `klog`.
Instead of creating free goroutines and relying on `log.Fatal` to terminate the process if any of them fail,
this PR instead adds those goroutines to the existing `errgroup` and replaces those instances of `log.Fatal` with returned errors which can be bubbled up to the parent Cobra command and handled centrally, in https://github.com/jetstack/jetstack-secure/pull/599.
These changes have been extracted from https://github.com/jetstack/jetstack-secure/pull/593 for easier review.
Occupy the server listening port and observe that the process exits with a meaningful error message.
```console
python3 -m http.server 8081 &
$ POD_NAMESPACE=venafi ./preflight agent --output-path /dev/null …
```
> [VC-35738] Use errgroup for all go routines

- cmd/agent.go
- cmd/echo.go
- cmd/root.go
- pkg/agent/run.go
- pkg/echo/echo.go
- pkg/logs/logs.go
- pkg/logs/logs_test.go
This is a small part of a larger effort to allow the agent to use structured logging.
This will make it easier for platform administrators to parse the logs and to distinguish errors from info messages.
It also is a small part of an effort to use contextual logging instead of the legacy `log` module.
This will make it easier to test the log output of our code in unit tests.
The existing code uses `log.Fatal` at the site of various errors to both print the error and to exit the process with code 1.
Instead the errors should be returned and bubbled back to the root command, which makes it easier to handle the errors in a consistent fashion and makes it easier to test the code that had previously caused the process to exit.
```console
$ git grep -i '\.fatal' | grep -v 't\.Fatal'
```
Example …
> [VC-35738] Bubble up the errors from sub-commands and handle errors centrally instead of using log.Fatal at multiple sites

- pkg/agent/run.go
- pkg/agent/run_test.go
In https://github.com/jetstack/jetstack-secure/pull/599#discussion_r1831289407 I caused a bug where the error from the errgroup Go routines is discarded rather than being logged and causing the process to exit.
How did I notice this bug? I noticed the problem while testing a revision of #603 where I wrapped nil DataGatherer.Run early return into an error...but was not seeing the resulting error. It turns out that is the wrong behaviour and I found an additional bug #605 so I have since reverted that change.
I didn't write automated test for this because I feel like we will be refactoring and simplifying the agent Run code in future and I just want to get the logging sorted out.
But I did test this manually as follows:
* Start an HTTP server on port 8081
```bash
python3 -m http.server 8081 …
```
> [VC-35738] Append errgroup errors to the error returned by Agent.Run

- pkg/agent/run.go
In https://github.com/jetstack/jetstack-secure/pull/601#discussion_r1831253638 I introduced a bug which caused the API server and VenafiConnection helper to exit as a result of the early return of some `DataGatherer.Run` implementations.
Tested using `hack/e2e/test.sh`.
Before this change, the venctl  installation part of the script failed,
because the healthz server gets quickly shutdown as a result of the Discovery DataGatherer.Run function returning and cancelling the errgroup.
This causes the Liveness check to fail, and the Helm install never succeeds.
After this change, the test script works again:
```console
$ ./hack/e2e/test.sh
...
{
"ts": 1730909040560.407,
"caller": "logs/logs.go:153",
"msg": "successfully gathered 10 items from \"k8s/namespaces\" datagatherer",
"source": …
```
> [VC-35738] Allow DataGatherer.Run to return without stopping the other errgroup Go Routines

- cmd/root.go
- pkg/logs/logs.go
- pkg/logs/logs_test.go
Instead of calling os.exit directly after parsing and finding an error in the logging flags, the error is now returned and handled the same way as errors that come from the `Run` function....they are logged using structured logging and the logs are flushed before the process exits.
I've adjusted the logs tests accordingly and modified them so that the log flag parsing and error handling in the tests matches the behaviour of the actual command.
Before:
```console
$ ./preflight agent --logging-format=foo
Error in logging configuration: format: Invalid value: "foo": Unsupported log format
$ echo $?
2
```
After:
```console
$ ./preflight agent --logging-format=foo
E1107 13:41:31.063915  281828 root.go:51] "Exiting due to error" err="Error in logging configuration: format: Invalid value: …
```
> [VC-35738] Remove os.Exit from the logs module

- deploy/charts/venafi-kubernetes-agent/templates/rbac.yaml
This is a small part of the work to remove spurious log messages: https://venafi.atlassian.net/browse/VC-33564
In https://github.com/jetstack/jetstack-secure/pull/507 we added a Firefly datagatherer to the venafi-kubernetes-agent chart configmap, but forgot to add RBAC to allow venafi-kubernetes-agent to read the firefly issuer resources.
This causes the following errors to be logged:
> datagatherer informer has failed and is backing off
> failed to list firefly.venafi.com/v1, Resource=issuers: issuers.firefly.venafi.com is forbidden: User "system:serviceaccount:venafi:venafi-kubernetes-agent" cannot list resource "issuers" in API group "firefly.venafi.com" at the cluster scope
> k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: failed to list firefly.venafi.com/v1, Resource=issuers: …
> [VC-33564] Add a Firefly clusterrole and clusterrolebinding to the venafi-kubernetes-agent chart

- examples/cert-manager-agent.yaml
I often try the `examples/cert-manager.yaml` for testing but the resource versions are wrong so it logs tons of errors.
Before:
```console
$ go run ./ agent --install-namespace venafi --one-shot --output-path out.master.js --api-token should-not-be-required  --agent-config-file examples/cert-manager-agent.yaml
2024/11/08 09:37:30 Preflight agent version: development ()
2024/11/08 09:37:30 Using the Jetstack Secure API Token auth mode since --api-token was specified.
2024/11/08 09:37:30 Using deprecated Endpoint configuration. User Server instead.
2024/11/08 09:37:30 error messages will not show in the pod's events because the POD_NAME environment variable is empty
2024/11/08 09:37:30 starting "k8s/secrets.v1" datagatherer
2024/11/08 09:37:30 starting …
```
> [VC-33564] Fix unknown resource errors when using the cert-manager config example

- cmd/root.go
- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/agent/run.go
The aim of this PR is to remove the stdlib `log` package and the use of the legacy `github.com/jetstack/jetstack-secure/logs.Log` variable, from the `agent` package. 
I'll create followup PRs to remove `logs.Log` elsewhere in the code, and ultimately remove that global variable.
```console
$ go test ./cmd/... -v
=== RUN   TestAgentRunOneShot
agent_test.go:41: Running child process
agent_test.go:59: STDOUT
I1107 16:10:35.015613  305780 run.go:57] "Starting" logger="Run" version="development" commit=""
I1107 16:10:35.017213  305780 config.go:395] "Using the Jetstack Secure API Token auth mode since --api-token was specified." logger="Run"
I1107 16:10:35.017789  305780 run.go:115] "Healthz endpoints enabled" logger="Run.APIServer" addr=":8081" path="/healthz"
I1107 16:10:35.017860  305780 …
```
> [VC-35738] Use klog and logr logger instead of log in the agent package

- pkg/datagatherer/k8s/cache.go
- pkg/datagatherer/k8s/cache_test.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/logs/logs.go
The aim of this PR is to remove the remaining references to the `logs.Log` variable and replace them with context derived `logr.Logger` calls.
I haven't given much thought to the log levels because I think we're going to be removing most of the messages about missing CRDs and permissions errors in another feature.
```console
$ go test ./pkg/datagatherer/k8s/... -v -run TestNoneCache -count 1
=== RUN   TestNoneCache
cache.go:53: E1107 17:57:50.964580] Cache update failure err="not a cacheResource type: *k8s.notCachable missing metadata/uid field" operation="add"
cache.go:66: E1107 17:57:50.964680] Cache update failure err="not a cacheResource type: *k8s.notCachable missing metadata/uid field" operation="update"
cache.go:80: E1107 17:57:50.964689] Cache update failure err="not a …
```
> [VC-35738] Replace logs.Log with logr.Logger in the remaining code

- pkg/agent/run.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/logs/logs.go
- pkg/logs/logs_test.go
The aims of this PR are:
* Make it clearer to the user what the `--verbosity` values mean in practice.
* Make it clear what the default `--verbosity` value is.
* Make it clearer to developers which `V()` value to use when they add new log messages.
* Make the `V()` values more consistent.
* Reduce the number of Info log messages that the agent prints by default.
> [VC-35738] Define well known log verbosity values and log less by default

- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
- deploy/charts/venafi-kubernetes-agent/values.schema.json
- deploy/charts/venafi-kubernetes-agent/values.yaml
- pkg/agent/config.go
- pkg/agent/run.go
- pkg/datagatherer/k8s/dynamic.go
- pkg/datagatherer/k8s/dynamic_test.go
Some annotations and labels contain sensitive information. A well-known example is the `kubectl.kubernetes.io/last-applied-configuration` annotation. We already exclude this annotations from Secret resources, but we have found that customers use other sensitive annotations and labels that they would like to not be sent to the Venafi Control Plane API.
A realistic example lies in the Kapp project. The Kapp project uses four annotations that all start with `kapp.k14s.io/original*` as seen in [1]. These annotations are similar to `kubectl.kubernetes.io/last-applied-configuration` in that they may contain sensitive information. The annotations would look like this:
```yaml
annotations:
kapp.k14s.io/original: |
{"apiVersion":"v1","kind":"Secret","spec":{"data": {"password": …
```
> VC-36950: It is now possible to exclude labels and annotations

- deploy/charts/venafi-kubernetes-agent/templates/rbac.yaml
The RBAC shipped with venafi-kubernetes-agent contained a syntax error which prevents the OpenShift Routes from being collected.
Users would have seen the following errors:
> k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: failed to list route.openshift.io/v1, Resource=routes: routes.route.openshift.io is forbidden: User \"system:serviceaccount:venafi:venafi-kubernetes-agent\" cannot list resource \"routes\" in API group \"route.openshift.io\" at the cluster scope
The RBAC API Group field is documented as follows:
```console
$ kubectl explain clusterrole.rules.apiGroups
GROUP:      rbac.authorization.k8s.io
KIND:       ClusterRole
VERSION:    v1
FIELD: apiGroups <[]string>
DESCRIPTION:
APIGroups is the name of the APIGroup that contains the resources.  If
multiple API groups are …
```
> [VC-33564] Fix the invalid API group rule for clusterrole venafi-kubernetes-agent-openshift-reader

- hack/e2e/values.venafi-kubernetes-agent.yaml
- pkg/client/client_venconn.go
- pkg/logs/logs.go
I assume that the controller-runtime logs were being discarded.
With this change I hope to find some controller-runtime logs among the e2e test logs.
```console
$ make test-e2e-gke
...
{
"ts": 1732123466929.3813,
"caller": "metrics/metrics.go:97",
"msg": "cache not synced yet, skipping metrics venaficonnection_*",
"source": "controller-runtime",
"v": 0
}
...
{"ts":1732123472568.4834,"caller":"agent/run.go:409","msg":"Data sent successfully","v":0,"logger":"Run.gatherAndOutputData.postData"}
```
That single message seems to come from venafi-connection-lib, so perhaps it's misleading to label these logs with `source: "controller-runtime"`:
* https://github.com/jetstack/venafi-connection-lib/pull/146
* https://github.com/jetstack/venafi-connection-lib/blob/13c2342fe0140ff084d2aabfd29ae3d10721 …
> [VC-36032] Configure controller-runtime to log with klog

- pkg/agent/config.go
- pkg/agent/config_test.go
- pkg/client/client_venafi_cloud.go
- pkg/client/client_venconn.go
- pkg/client/client_venconn_test.go
Ref: [VC-37264](https://venafi.atlassian.net/browse/VC-37264 "Disable agent's compression")
On Nov 21, 2024, the Production Engineering team found that the test pipeline was failing due to venctl 1.15.3. They rolled back to venctl 1.15.2, which made the pipeline work again.
After investigating, we found that the Agent's compression feature broke the Agent. The Agent sends its upload request using `Content-Encoding: gzip`, but the server doesn't process this header and doesn't decompress the body. It copies the contents of the request's body to a bucket without checking its validity. When the backend asynchronously tries to process the contents of the upload, it fails with the error:
```
json: invalid character \u001f as token
```
After some consideration, we decided to remove entirely the …
> VC-37264: Disable compression to give us time to work on a fix

- README.md
I'm always tripping over this: It looks like another action, but isn't. It's an information instead. I propose to move the information to a note and reformulate this item as an action instead:
Before
```md
2. A GitHub action will see the new tag and do the following:
- Build and publish the container image at `quay.io/jetstack/venafi-agent`,
- Build and publish the Helm chart at `oci://quay.io/jetstack/charts/venafi-kubernetes-agent`,
- Create a draft GitHub release,
- Upload the Helm chart tarball to the GitHub release.
```
After
```md
2. Wait until the GitHub Actions finishes.
```
> readme: move informative stuff out of the list of actions in the release process

- hack/e2e/test.sh
I adapted the commands that @maelvls described in the PR #628.
The E2E test script will now create a TLS certificate in a Secret (not managed by cert-manager) with a unique common name,
and wait for a certificate with that unique common name to appear in the  Venafi Cloud API.
Signifying that the venafi-kubernetes-agent has successfully uploaded the data and that the TLSPK backend has successfully processed the data.
```console
$ make test-e2e-gke
...
{
"ts": 1732293943910.6917,
"caller": "cache/reflector.go:368",
"msg": "Caches populated for *v1alpha1.VenafiConnection from k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243",
"v": 2
}
{"ts":1732293944460.7644,"caller":"agent/run.go:409","msg":"Data sent successfully","v":0,"logger":"Run.gatherAndOutputData.postData"} …
```
> [VC-37264] Update E2E test to check for certificate in the API

- README.md
Olu and I found that the table was out of date and didn't reflect the real flow.
For context, the real OCI helm chart flow is as follows:
```
v1.1.0 (Git tag in the jetstack-secure repo)
└── oci://quay.io/jetstack/charts/venafi-kubernetes-agent --version 1.1.0 (GitHub Actions in the jetstack-secure repo)
├── oci://us.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent (Enterprise Builds's GitHub Actions)
└── oci://eu.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent (Enterprise Builds's GitHub Actions)
├── oci://registry.venafi.cloud/charts/venafi-kubernetes-agent --version 1.1.0 (Harbor Replication)
└── oci://private-registry.venafi.cloud/charts/venafi-kubernetes-agent --version 1.1.0 (Harbor Replication)
└── …
```
> [Release 1.4.0] Clarify the table with the OCI Helm charts

- pkg/agent/config.go
- pkg/agent/config_test.go
In https://github.com/jetstack/jetstack-secure/issues/549 @hawksight wrote:
> ...we are missing one important piece [of logged information] when connecting to TLSPK on VCP, the client-id
I've added client-id to the log messages when the configuration resolver selects Venafi Cloud Authentication.
But in the interests of reducing the overwhelming quantity of log messages, I've also changed that log message to only be shown at debug log level `--log-level=1`.
I've also associated this PR with `[VC-36032] AGENT: Enhanced troubleshooting through improved logging`.
```console
$ go run ./ agent --install-namespace default --private-key-path /dev/null --client-id foo --agent-config-file examples/cert-manager-agent.yaml  --output-path /dev/null -v1
I1120 15:50:50.273235  185320 run.go:59] …
```
> [VC-36032] Log the client-id when VenafiCloudKeypair authentication is used

- deploy/charts/venafi-kubernetes-agent/README.md
- deploy/charts/venafi-kubernetes-agent/values.schema.json
- deploy/charts/venafi-kubernetes-agent/values.yaml
- hack/e2e/values.venafi-kubernetes-agent.yaml
- pkg/agent/config_test.go
- pkg/agent/run.go
- pkg/client/client.go
- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_venafi_cloud.go
- pkg/client/client_venconn.go
- pkg/client/client_venconn_test.go
- pkg/logs/logs.go
- pkg/logs/logs_test.go
- pkg/testutil/envtest.go
- Improve orderly shutdown by abandoning ongoing requests to Venafi when the context is cancelled
- Make it easier to debug venafi data upload problems by allowing the request details to be logged with `--log-level=6`.
```bash
go run . agent --install-namespace venafi --one-shot --input-path out.json  --venafi-connection venafi-components -v6
```
> I1127 09:58:16.779115  318776 metrics_transport.go:113] "outgoing http request succeeded" source="controller-runtime" method="POST" uri="https://api.venafi.eu/v1/oauth2/v2.0/9a0cab61-2b00-11ee-ba09-0733b0fe5adc/token" status="200 OK" duration="582.557289ms"
> **I1127 09:58:17.313520  318776 round_trippers.go:553] POST https://api.venafi.eu/v1/tlspk/upload/clusterdata/no?name=my_cluster 200 OK in 502 milliseconds**
> I1127 09:58:17.313624 …
> [VC-36032] Pass the context to Venafi clients and enable debug roundtripper

- pkg/agent/config_test.go
- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_venafi_cloud.go
In [VC-36032](https://venafi.atlassian.net/browse/VC-36032) we aim to provide:
> Enhanced troubleshooting through improved logging
By adding user-agent headers to *all* HTTP requests, it will allow the Venafi platform team to know which version of the agent is making requests to the resource and auth APIs, by analysing the request headers among the server logs.
I tried writing tests for this, but the it would have required some significant refactoring of the client code,
for example there's no easy way to intercept the  Auth0 client request made by the Jetstack-Secure client in client_oauth.go.
That's a bit of a lame excuse, but I would like to propose that we refactor the Venafi client code in a followup PR and at the same time add tests which verify that all the flavours of Venafi …
> [VC-36032] Set User-Agent header containing the agent version in all HTTP requests

- .github/workflows/govulncheck.yaml
- .github/workflows/make-self-upgrade.yaml
- .github/workflows/release.yml
- OWNERS_ALIASES
- hack/e2e/test.sh
- klone.yaml
- make/00_mod.mk
- make/02_mod.mk
- make/_shared/go/base/.github/workflows/govulncheck.yaml
- make/_shared/helm/crds.mk
- make/_shared/helm/crds_dir.README.md
- make/_shared/helm/helm.mk
- make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
- make/_shared/repository-base/base/OWNERS_ALIASES
- make/_shared/tools/00_mod.mk
Manual Makefile modules upgrade.
> Upgrade Makefile modules

- .github/workflows/tests.yaml
- README.md
The badge wasn't showing the latest job run from master. It was green because the workflow was green due to the pull requests. 
Before:
After:
The badge is now grayed out becuase the "tests" workflow doesn't currently run on the master branch due to probable copy-paste issue (it was set to trigger on the main branch, but this project doesn't have a main branch).
Fixes #632
> README: badge wasn't showing the latest job run from master

- pkg/kubeconfig/kubeconfig.go
The function was overly complex, the underlying struct was already differentiating between an empty/ non-empty kubeconfig value.
> Simplify LoadRESTConfig function

- pkg/client/client_api_token.go
- pkg/client/client_oauth.go
- pkg/client/client_venafi_cloud.go
- pkg/client/client_venconn.go
- pkg/version/version.go
This means we can be sure that the user agent is uniform across the codebase, making it easier to update in the future.
> feat: Use centralized function for setting user agent across codebase

- make/00_mod.mk
> Add OCI image annotations

- klone.yaml
- make/_shared/kind/kind.mk
- make/_shared/tools/00_mod.mk
- pkg/internal/cyberark/servicediscovery/discovery_test.go
> Run 'make upgrade-klone' and 'make generate'

- deploy/charts/venafi-kubernetes-agent/templates/configmap.yaml
Replicaset resources are ignored by the TLSPK backend service so there's no point collecting them.
In a Kind cluster with 20k Replicasets, this reduced the peak resident set memory usage from 522 MB to 85 MB.
> See testing section below. Other resources: 53 Nodes, 52 Deployments, 350 Pods, 4 Secrets
On a busy cluster where there are frequent Helm upgrades and / or  deployment rollouts, there may be a large number of Replicaset resources for previous revisions of each Deployment. This depends on the Deployment revisionHistoryLimit, which is 10 by default.
It may also depend on the `helm upgrade --history-max` value, which is 10 by default:
```bash
$ helm upgrade --help
...
--history-max int                            limit the maximum number of revisions saved per release. Use 0 for no …
```
> [VC-41078] Reduce memory usage by removing the Replicaset data gatherer from the default config

- make/test-unit.mk
* add line to print total coverage in test-unit
> VC-42286-add-total-%-cov

- pkg/internal/cyberark/dataupload/dataupload.go
- pkg/internal/cyberark/dataupload/mock.go
The API team discovered that sha3 is not supported by the AWS backend, so have reverted to sha256. 
I have also added the `x-amz-checksum-sha256` request header. It causes AWS S3 to verify that it has received the expected payload.
Ideally, that header would be required and be among the signed headers of the presigned URL, but the backend does not currently support that. See:
* https://github.com/aws/aws-sdk/issues/480
* https://github.com/aws/aws-sdk-go-v2/issues/2610
Before:
```
$ go test -v ./pkg/internal/cyberark/dataupload/... -run  Real -args -testing.v 6
=== RUN   TestPostDataReadingsWithOptionsWithRealAPI
round_trippers.go:632: I0819 17:46:29.965381] Response verb="GET" url="https://platform-discovery.integration-cyberark.cloud/api/v2/services/subdomain/tlskp-test" status="200 OK" …
```
> [VC-43403] Revert to using sha256 checksum to match latest snapshot-links API

- pkg/internal/cyberark/dataupload/mock.go
A follow up to #689 and pulls some other changes from #681, to make that PR less sprawling. 
I noticed the following problems with the mock dataupload API server.
- Remove unused logic, 
- use meaningful handler names
- more realistic responses
In another PR I may try and consolidate the various CyberArk API mocks into a separate package
> [VC-43403] Various improvements to the mock API server

- .github/workflows/tests.yaml
- README.md
- hack/e2e/test.sh
- hack/e2e/values.venafi-kubernetes-agent.yaml
- make/02_mod.mk
- make/_shared/tools/00_mod.mk
- make/extra_tools.mk
1. Add the test.sh script to be run by the CI
2. Add all dependencies required to execute the script in extra_tools.mk
3. Created a GCP account (via SNOW request) and setup inside it:
- A service account with manage GKE permissions, Write Image Repository Permissions and the relevant APIs enabled. 
- A JSON auth key for this account was set as a secret to the CI runner in `GCP_SA_KEY`
- A repository to push the images which the script builds
4. A valid API key for https://glow-in-the-dark.venafi.cloud/ was set as a CI secret in VEN_API_KEY_PULL
5. A valid VEN_ZONE was configured - mladen-test\Default. If this is not valid test would fail because the certificate request would be ignored.
6. Created two labels: `test-e2e` and `keep-e2e-cluster` - one to trigger the e2e test and the other to …
> [VC-35565] Automate the e2e script to run in CI
